/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Ics100.types";
import * as _1 from "./Ics100.client";
import * as _2 from "./Ics100.react-query";
import * as _3 from "./Ics100.provider";
import * as _4 from "./Ics101.types";
import * as _5 from "./Ics101.client";
import * as _6 from "./Ics101.react-query";
import * as _7 from "./Ics101.provider";
import * as _8 from "./contractContextProviders";
import * as _9 from "./contractContextBase";
import * as _10 from "./contracts-context";
export namespace SideContracts {
  export const Ics100 = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const Ics101 = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
  export const contractContextProviders = { ..._8
  };
  export const contractContextBase = { ..._9
  };
  export const contractsContext = { ..._10
  };
}